### ISSUE TITLE
how to use applyLinearImpulse ???

### ISSUE THREAD

**Issue by homatenbeo1990** [ymobe/rapanui#125]
how to use applyLinearImpulse in rapanui ????

**Comment by MattiaFortunati** [comment]
Hi homatenbeo1990,

you can check this sample:
https://github.com/ymobe/rapanui/blob/master/rapanui-samples/physics/rn-physics-forces.lua

:D

**Comment by homatenbeo1990** [comment]
Hi  MattiaFortunati
I use applyLinearImpulse to make the character jump up.
but that does not happen, I was wrong ???

My code : 
function Player:jump()
    if HUD:getIsJump() then
        self.body:setLinearVelocity( self.body:getLinearVelocity(), 0)
                self.body:applyLinearImpulse( 0, 80)
        print("xxxxxx", self.body:getLinearVelocity())
    end
end

**Comment by MattiaFortunati** [comment]
Hi,

I think your player is not moving because its weight is too big for the impulse force you are giving.
And also it would be better to specify center of impulse application.
Try to use

> self:applyLinearImpulse( 0, -10000,self.x,self.y)

I'm not sure of this, but this may explain the reason I used so big values in the sample

> ball:applyLinearImpulse(-10000, -100000, ball.x, ball.y)

also, remember you can call methods directly on the object like this:

> self: body:applyLinearImpulse(0,80,self.x,self.y)

Let me know! :D
