### ISSUE TITLE
Re-Use Textures / Texture-manager

### ISSUE THREAD

**Issue by derhannes** [ymobe/rapanui#16]
I've already posted this on the Moai-Forum:
It would be great if RNFactory would accept already created images/animations to save memory.

Maybe a Texture-Manager would be the best solution, avoiding multiple instances of the same texture-file and avoiding unnecessary texture swichting by sorting draw-calls (afaik texture switching makes things slow)

**Comment by eljeko** [comment]
Hi derhannes,

Do you have a pseudocode to propose and/or functions signature in mind? I'll very happy to receive suggestions.

thank you for opening request on github.

**Comment by derhannes** [comment]
Hi eljeko,
thanks for answering and all the work you and your team put into rapanui!

A quite simple approach would be something like:
    texture_animal  = RNFactory.createTexture("wolf.png") -- Or maybe RNTextureManager.addTexture("wolf.png")
    animal = RNFactory.createAnim(texture_animal, 128,128, 100, 100, 0.5, 0.5) -- Or get the texture from RNTextureManager
    animal2 = RNFactory.createAnim(texture_animal, 128,128, 100, 100, 0.5, 0.5)
    animal3 = RNFactory.createAnim(texture_animal, 128,128, 100, 100, 0.5, 0.5)

But I have no idea at the moment, how this would work internally in the RNFactory..
I'm pretty new to LUA (currently switching over from Java development), so please bear with me :)

**Comment by eljeko** [comment]
ok I got you :)

don't worry, we are here to make things better with the help of other developers.

**Comment by derhannes** [comment]
Great :)

I'm not sure if to post a new issue on this:
I would love to be able to control the OpenGL blend modes per RNObject, is this (or will this be) possible?
Also a way to colorize objects would be nice. (e.g. to create dynamic drop-shadows or different colored versions to show to which player a certain unit belongs, etc.)

**Comment by eljeko** [comment]
yes good idea. But it could require a bit more of effort to implement now. 
I'm looking at moai examplesnow, let us study how we could put that stuff into RapaNui.
Do you have exeperience in that field?

**Comment by derhannes** [comment]
The color thing is done in: moai-sdk\samples\basics\prop-color
are props used in rapanui?

I'm searching for a way to change the blend modes now.. ..I'm not an OpenGL expert, but I've used this in Java with LWJGL before..

**Comment by derhannes** [comment]
It seems like this can be done with props too:
http://getmoai.com/docs/class_m_o_a_i_prop2_d.html

**Comment by ghost** [comment]
Just a heads up.
I tried to do reuse textures (https://github.com/anddrewscott/Moai-work/blob/master/display.lua#L44 ) but I seam to remember that when setRect() is changed, the MOAIGfxQuad2D changes. Thus, ever instance of that texture is resized.

**Comment by Sylph** [comment]
I've actually just done this with prop on my dev fork, derhannes. I'm using it in conjunction with props created from texturepacker files right now.

So I just do something like 
RNFactory.createImageFromMoaiProp(textureLoader:newSprite("MainMenuBG"), { top = RNFactory.height, parentGroup = group })

**Comment by makotok** [comment]
Hello.

For reference, we implemented a simple way rather than a managed texture.
Will be used and to specify the path to the texture, the texture is cached.
In addition, if there are no references, then the texture will be destroyed in gc.
This is done in the implementation of the onDestory of the moai.

https://github.com/makotok/rapanui/commit/6702b968d2cb6c30b4c5a9aa42659f7cbe619ec6

**Comment by makotok** [comment]
Made a mistake a little.
Modified as follows by the addition.

https://github.com/makotok/rapanui/commit/91d2873a06ff6606b94acefb889355eedfac7b8b

**Comment by MattiaFortunati** [comment]
Check this commit in the rapanuidev branch
https://github.com/ymobe/rapanui/commit/652621e61d2d22c17609fad06ba960ce3f0ba9c6
animations can be used as atlas, too.

We are going to improve this soon.

Have Fun

**Comment by Sylph** [comment]
I haven't gone through that completely, but doesn't that limit the spritesheet to only contains sprite of the same size? Why not let us pass a deck or a prop, so that generic libraries for moai that create a deck or a prop could also be used?

**Comment by MattiaFortunati** [comment]
Hi.
Yes, this limits spritesheets, at the moment.

I'm working on a simple texture Atlas which will handle any image size.
This will be a basic Atlas, so we can write any packer parser we want.

Also, RNFactory.createImage will accept a deck created outside RNFactory so it will be possible to use Moai decks to create RNObjects.

(at the moment RNFactory returns a deck, too, which can be reused instead of the path).

**Comment by Sylph** [comment]
Great to hear about the texture atlas. :)
I see the deck stuff, I'll have to check about using it to get the props/frames.

**Comment by Sylph** [comment]
I see that it has been in for a few days now, so this issue could be closed?
One last question though, when the resource get allocated/loaded, it doesn't seem like there's anything handling clearing the RNGRaphicsManager.gfx. Are we supposed to do that manually?

**Comment by MattiaFortunati** [comment]
Hi, 
I'll close the issue as soon as the rapanuidev branch will be merged into the master.
I'll add the remove gfx function for the RNGraphicsManager asap.

**Comment by makotok** [comment]
Hello.

When you share a MOAITileDeck2D, or does not affect the other RNObject if you change the tileSize?
Operations on Deck, which contributes to its other RNObject.

**Comment by MattiaFortunati** [comment]
@Sylph 
I've added the RNFactory.removeAsset(path) function, correctly working for images, animations,maps and atlases, also with physics on them. Check the sample code here:
https://github.com/ymobe/rapanui/blob/rapanuidev/rapanui-samples/basic/rn-deallocate.lua
Thanks for the suggestion!

Due to a Moai known bug we cannot deallocate fonts, but the code for this is already in RapaNui ^^

@makotok 
I'm working on it, thanks for the suggestion!

**Comment by MattiaFortunati** [comment]
@makotok 
Check this commit:
https://github.com/ymobe/rapanui/commit/300ddffda01d246a1c81c1810b83dc00331df700

Since scales now are applied to props and not to decks, objects sharing the same deck can have different transformations.
scaleX, scaleY, flipHorizontal(),flipVertical() are now available for any kind of image : images, animations and anything coming from atlases.
Also if they share the same deck. 

Have Fun!

**Comment by Sylph** [comment]
Wonderful, thanks for all the hard work. :)
Now just one more thing left that'd make rapanui+moai better than the alternatives (the group nesting, which i'll follow the other issue on). Though I could always implement that myself too. :)

**Comment by makotok** [comment]
@MattiaFortunati 
Thank you for support.
Perfect!
