### ISSUE TITLE
Reusing texture on multiple scenes lead to them being loaded multiple times.

### ISSUE THREAD

**Issue by Sylph** [ymobe/rapanui#50]
Right now I'm reusing a texturepacker asset for main menu and credit scenes background. It currently keeps reloading the assets, as i switch back and forth between main menu scene and credit scene. The idea is to hopefully use a single  texturepacker file for all the menu screens, and just remove it when i enter a game/exit menu.

I've fixed it with getAlreadyAllocated, but shouldn't this just be automatic?

```
    if not RNGraphicsManager:getAlreadyAllocated(scene.assets.atlasPath) then
        RNFactory.createAtlasFromTexturePacker(scene.assets.atlasPath, scene.assets.atlasLua)
    end
```

So I'm suggesting to adjust createAtlasFromTexturePacker so that it is more like

```
if not RNGraphicsManager:getAlreadyAllocated(image) then
        RNGraphicsManager:allocateTexturePackerAtlas(image, file)
end
```

**Comment by MattiaFortunati** [comment]
Hi, 

this is not a bug. I've made it like this so user can choose when to allocate texturepacker textures.
At the moment you are supposed to call createAtlasFromTexturePacker only once in the loading menu.

That's because it's wrong to create atlas more than once if you don't deallocate it first.

I did not developed this like images because you may want to create/remove images dynamically so automatic cache is required while you are supposed to allocate atlas once and create images from it.

So, it's logically wrong you want to create atlas in main menu while not doing it in a loading screen.
(And yes, if you want to do so, you have to manually do checks.)

Thanks for the issue, maybe we can change this in the future.

Have a nice day!

**Comment by Sylph** [comment]
Ah I see, thanks for the time. :)
Well, feel free to just close this. ^^
