### ISSUE TITLE
Physics event.phase="begin" is getting called multliple times

### ISSUE THREAD

**Issue by Jerry77oz** [ymobe/rapanui#65]
I have a collision function that is getting called multiple times, causing errors to go off when remove() gets inevitably called several times. 

I have a check for event.phase=="begin" but it still is passing through more than once.

I'm still new to both MOAI and RapaNui so I'm not sure what I may have missed. Below are snippets of the object causing the problems.

Any help would be greatly appreciated, thanks!

``` lua
function missile:onLocalCollide(event)
        if (self ~= nil) and (event.other ~= nil) and (event.phase == "begin")  then
            -- handle impact logic
            self:remove()
        end
    end
```

``` lua
--Set up physics data
    missile.physicsData = (require "assets/spriteSheets/physics/fish").physicsData(missile.config.BEAR_FISH_SCALE_FACTOR)
    RNPhysics.createBodyFromImage(missile, missile.physicsData:get("missile-fish"))
    missile.restitution = 0.5

    --Add collision detection pulled from missileEnenmy
    missile.collision = missile.onLocalCollide
    missile:addEventListener("collision")
```

**Comment by Jerry77oz** [comment]
Hmm, I thought it might've been as well when I found "began" as I looked through RNPhysics.lua; but when I've tried it, it just never holds true.

I tried `print("event.phase")` and the following came up

```
begin
begin
pre_solve
pre_solve
begin
begin
pre_solve
pre_solve
post_solve
post_solve
post_solve
post_solve
end
end
end
end
```

**Comment by meapps** [comment]
but try to change your function to 
function missile:onLocalCollide(self, event)
if (event.self ~= nil) and (event.other ~= nil) and (event.phase == "begin") then
 self:remove()
end
 end

**Comment by Jerry77oz** [comment]
Ok, just tried it but after using both self and event.self I got the same results, but they both do point to the same object/table.

I tested with this:

``` lua
        print(self)
        print(event.self)
```

**Comment by MattiaFortunati** [comment]
Hi Jerry77oz,

I've just had a simple test and this is not happening with physics objects having just one fixture.
But with more complex objects, you are right, "begin" event is called more than one time.

That's because "begin" event is called for each fixture of the colliding object.
ex: if a car hits a ground, begin is called one time for back wheel and one time for fron wheel else if they are wheels of the same object.
This is happening because you may need to receive the "begin" event for each fixture.

Strange things can happen if you remove an object inside the collision event (it's not suggested to do so).
It's not so good but maybe you can have a timer starting in begin collision which will remove the object in 0,1 seconds. :S

However 

> if (event.self ~= nil) and (event.other ~= nil) and (event.phase == "begin") then
> self:remove()
> end

the code above won't work. 
But If you perform your check using this:

> if event.self.prop~=nil then
> self:remove()
> end

it should work, and this is the best way to do what you need,at the moment.

Let me know,

Mattia ;D

**Comment by Jerry77oz** [comment]
Hey Mattia,

Yes, that worked! 

It does make sense now that you mention it, I had the object with another 'sensor' object but I never once thought that would be triggering the multiple 'begin's.

I'll also try to figure out a better way to remove the objects.

Thank you all for the all help!
Jerry
